### ISSUE TITLE
Final CSS Challenge

### ISSUE THREAD

**Issue by NickBanken** [becodeorg/free2code#6]
@pixeline It's a good final exercise, but I noticed the following:
- Is it supposed to be just a mobile version of the site? Personally I would let them make both since they will see responsiveness.
- We will have to make sure they know how to make an hamburger menu before they reach to this stage. (Perhaps the positioning section so they can re-use it).
- The logo is missing in the image folder.

Other than that I think it's a worthy challenge for them!

**Comment by pixeline** [comment]
> @pixeline It's a good final exercise, but I noticed the following:
> 
> * Is it supposed to be just a mobile version of the site? Personally I would let them make both since they will see responsiveness.

I see several issues: 
- I don't have a mockup for the mobile version
- i'm not sure the code editor included in the platform allows to resize the viewport to test responsiveness
- the responsive part is a nice-to-have in my opinion: the goal of the training is to give them a taste at coding websites.

So if you are okay, let's not worry about it for now ?

> * We will have to make sure they know how to make an hamburger menu before they reach to this stage. (Perhaps the positioning section so they can re-use it).
> * The logo is missing in the image folder.

Good catch! i just added it now.

> Other than that I think it's a worthy challenge for them!

**Comment by pixeline** [comment]
@NickBanken if you are ok, can you close the issue so I know it is solved ?

**Comment by NickBanken** [comment]
We will leave it for now and see how the editor works later, once we know how it works, I can still tell them to do something extra on the job.

Cheers!
